# -*- coding: utf-8 -*-
"""Toxic_Video_App (4) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OvwkhjB7BdqUewubsAqmCA50TuK69hNY

# NLP - Video Toxicity Analysis
It does not require GPU access to run this notebook.

This notebook is authored by [Anmol Talwar](https://www.linkedin.com/in/anmol-talwar-922061164/) - Founder and Trainer at Talent Catalyst AI

Visit the blogs on [Talent Catalyst AI](https://talentcatalystai.com/) to learn more on New Gen Technology
"""

!pip install SpeechRecognition pydub
!pip install moviepy

import pandas as pd
import numpy as np

import re
import string

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score ,confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB, GaussianNB


import seaborn as sns
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings('ignore')

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer, PorterStemmer
import string
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')


import speech_recognition as sr

from moviepy.editor import *

def expand_contractions(text):
    # Contractions mapping
    contractions = {
        "can't": "cannot",
        "won't": "will not",
        "n't": " not",
        "'ll": " will",
        "'ve": " have",
        "'s": " is",
        "'re": " are",
        "'d": " would",
        "'m": " am"
    }
    # Replace contractions with their expanded forms
    for contraction, expansion in contractions.items():
        text = text.replace(contraction, expansion)
    return text

def clean_text(text):
    # Lowercasing
    text = text.lower()

#     Expand contractions
    text = expand_contractions(text)

    # Tokenization
    tokens = word_tokenize(text)

    # Removing numerals and special characters
    tokens = [re.sub(r'[^a-zA-Z]', '', word) for word in tokens]

    # Removing punctuation
    tokens = [word for word in tokens if word not in string.punctuation]

    # Removing stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]

    # Removing numerals
    tokens = [word for word in tokens if not word.isdigit()]

    # Stemming
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]

    # Join tokens back into a string
    cleaned_text = ' '.join(tokens)

    return cleaned_text

def make_test_predictions(df, classifier, vect):

    cols_target = ['toxic','severe_toxic','obscene','threat','insult','identity_hate']

    df.comment_text = df.comment_text.apply(clean_text)

    X_test = df.comment_text
    X_test_transformed = vect.transform(X_test)

    y_test_pred = classifier.predict_proba(X_test_transformed)
    temp = classifier.predict(X_test_transformed)

    a = np.array(y_test_pred[0])
    sns.barplot(x = cols_target,y =a*100)
    plt.ylim((0,100))

    if np.any(y_test_pred[0] > 0.5):
       plt.title('The comment is Toxic')

    else :
      plt.title('The comment is Non Toxic')

    label_prob_dict = {}

    for label, probability in zip(cols_target, y_test_pred[0]):
        if probability > 0.5:
            label_prob_dict[label] = probability

    if len(label_prob_dict)>0:
        final_output = "The Audio is Toxic with the below categories and respective intensities - \n"
        for l in label_prob_dict.keys():
            final_output += f"{l}: {round(label_prob_dict[l]*100)} \n"
    else:
        final_output = "The Audio is Non-Toxic"
    print(y_test_pred[0])
    print(label_prob_dict)
    return final_output

def predict_toxic(text, model, vect):
    comment_text = text
    comment ={'id':[1],'comment_text':[comment_text]}
    comment = pd.DataFrame(comment)
    return make_test_predictions(comment, model, vect)

def speech_to_text(output_path):
    filename = output_path
    r = sr.Recognizer()
    with sr.AudioFile(filename) as source:
        # listen for the data (load audio to memory)
        audio_data = r.record(source)
        # recognize (convert from speech to text)
        text = r.recognize_google(audio_data)
        print(text)
        return text

from moviepy.video.io.VideoFileClip import VideoFileClip
def convert_video_to_wav(video):

    # Loading the Video
    vc = VideoFileClip(video)

    # Extract audio from the video
    audio = vc.audio

    # Set the output file path for the .wav file
    output_path = "/content/temp.wav"

    # Write the audio to a .wav file
    audio.write_audiofile(output_path)

    # Close the video file
    vc.close()

    text = speech_to_text(output_path)
    return text

# Input Parameters

import pickle

with open('/content/Toxic_lightgbm_model (1).pkl', 'rb') as fin:
    model = pickle.load(fin)

with open('/content/Toxic_tfidf_vectorizer (1).pkl', 'rb') as fin:
    vect = pickle.load(fin)

video = "/content/WhatsApp Video 2026-07-07 at 1.29.03 PM.mp4"

text  = convert_video_to_wav(video)
output = predict_toxic(text, model, vect)
print(output)

"""**App - Gradio**"""

!pip install gradio

import gradio as gr

def analyze_video(video_file):
    # Function to process the video file and get the text transcript
    text_transcript = convert_video_to_wav(video_file)

    # Function to analyze toxicity of the text transcript
    sentiment = predict_toxic(text_transcript, model, vect)

    return text_transcript, sentiment


demo = gr.Interface(
    fn=analyze_video,
    inputs=[gr.Video()],
    outputs=[gr.Textbox(label="Video Transcript", lines=5), gr.Textbox(label="Toxicity Analysis", lines=5)]
)

if __name__ == "__main__":
    demo.launch(debug=True)
    # demo.launch()

